# Generated by Django 5.1.4 on 2024-12-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_workprogress_icon_url_alter_workprogress_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprogress',
            name='icon_url',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
    ]
